-- Only seed if table is empty (first run)
INSERT INTO MEDICINES (NAME, CATEGORY)
SELECT * FROM (VALUES
    ('Paracetamol', 'Analgesic'),
    ('Ibuprofen', 'NSAID'),
    ('Amoxicillin', 'Antibiotic'),
    ('Azithromycin', 'Antibiotic'),
    ('Ciprofloxacin', 'Antibiotic'),
    ('Metformin', 'Antidiabetic'),
    ('Glimepiride', 'Antidiabetic'),
    ('Amlodipine', 'Antihypertensive'),
    ('Losartan', 'Antihypertensive'),
    ('Telmisartan', 'Antihypertensive'),
    ('Atorvastatin', 'Statin'),
    ('Rosuvastatin', 'Statin'),
    ('Omeprazole', 'Antacid'),
    ('Pantoprazole', 'Antacid'),
    ('Ranitidine', 'Antacid'),
    ('Domperidone', 'Antiemetic'),
    ('Ondansetron', 'Antiemetic'),
    ('Cetirizine', 'Antihistamine'),
    ('Levocetirizine', 'Antihistamine'),
    ('Fexofenadine', 'Antihistamine'),
    ('Montelukast', 'Antiasthmatic'),
    ('Salbutamol', 'Bronchodilator'),
    ('Prednisolone', 'Corticosteroid'),
    ('Dexamethasone', 'Corticosteroid'),
    ('Methylprednisolone', 'Corticosteroid'),
    ('Aspirin', 'Antiplatelet'),
    ('Clopidogrel', 'Antiplatelet'),
    ('Metoprolol', 'Beta-blocker'),
    ('Atenolol', 'Beta-blocker'),
    ('Propranolol', 'Beta-blocker'),
    ('Diclofenac', 'NSAID'),
    ('Naproxen', 'NSAID'),
    ('Tramadol', 'Analgesic'),
    ('Gabapentin', 'Anticonvulsant'),
    ('Pregabalin', 'Anticonvulsant'),
    ('Alprazolam', 'Anxiolytic'),
    ('Diazepam', 'Anxiolytic'),
    ('Sertraline', 'Antidepressant'),
    ('Fluoxetine', 'Antidepressant'),
    ('Escitalopram', 'Antidepressant'),
    ('Levothyroxine', 'Thyroid'),
    ('Metronidazole', 'Antibiotic'),
    ('Doxycycline', 'Antibiotic'),
    ('Cephalexin', 'Antibiotic'),
    ('Cefixime', 'Antibiotic'),
    ('Rabeprazole', 'Antacid'),
    ('Sucralfate', 'Gastroprotective'),
    ('Lactulose', 'Laxative'),
    ('Bisacodyl', 'Laxative'),
    ('Iron Folic Acid', 'Supplement'),
    ('Calcium + Vitamin D3', 'Supplement'),
    ('Vitamin B Complex', 'Supplement'),
    ('Multivitamin', 'Supplement'),
    ('Insulin Glargine', 'Antidiabetic'),
    ('Sitagliptin', 'Antidiabetic'),
    ('Pioglitazone', 'Antidiabetic'),
    ('Furosemide', 'Diuretic'),
    ('Hydrochlorothiazide', 'Diuretic'),
    ('Spironolactone', 'Diuretic'),
    ('Warfarin', 'Anticoagulant')
) AS t(NAME, CATEGORY)
WHERE (SELECT COUNT(*) FROM MEDICINES) = 0;

-- Seed symptoms
INSERT INTO SYMPTOMS (NAME)
SELECT * FROM (VALUES
    ('Fever'),
    ('Cough'),
    ('Headache'),
    ('Body Pain'),
    ('Cold / Runny Nose'),
    ('Sore Throat'),
    ('Vomiting'),
    ('Diarrhea'),
    ('Chest Pain'),
    ('Abdominal Pain'),
    ('Breathlessness'),
    ('Dizziness'),
    ('Fatigue'),
    ('Skin Rash'),
    ('Joint Pain')
) AS t(NAME)
WHERE (SELECT COUNT(*) FROM SYMPTOMS) = 0;

-- Seed sub-symptoms (references symptom IDs by name lookup)
INSERT INTO SUB_SYMPTOMS (NAME, SYMPTOM_ID)
SELECT ss.NAME, s.ID FROM (VALUES
    ('High Grade', 'Fever'),
    ('Low Grade', 'Fever'),
    ('Intermittent', 'Fever'),
    ('With Chills', 'Fever'),
    ('Dry Cough', 'Cough'),
    ('Productive Cough', 'Cough'),
    ('With Phlegm', 'Cough'),
    ('Chronic Cough', 'Cough'),
    ('Frontal', 'Headache'),
    ('Temporal', 'Headache'),
    ('Migraine', 'Headache'),
    ('With Nausea', 'Headache'),
    ('Generalized', 'Body Pain'),
    ('Muscle Pain', 'Body Pain'),
    ('Back Pain', 'Body Pain'),
    ('Sneezing', 'Cold / Runny Nose'),
    ('Nasal Congestion', 'Cold / Runny Nose'),
    ('Watery Discharge', 'Cold / Runny Nose'),
    ('Pain on Swallowing', 'Sore Throat'),
    ('Redness', 'Sore Throat'),
    ('With Nausea', 'Vomiting'),
    ('Projectile', 'Vomiting'),
    ('After Food', 'Vomiting'),
    ('Watery', 'Diarrhea'),
    ('Bloody', 'Diarrhea'),
    ('With Cramps', 'Diarrhea'),
    ('Left Side', 'Chest Pain'),
    ('On Exertion', 'Chest Pain'),
    ('At Rest', 'Chest Pain'),
    ('Upper Abdomen', 'Abdominal Pain'),
    ('Lower Abdomen', 'Abdominal Pain'),
    ('Cramping', 'Abdominal Pain'),
    ('On Exertion', 'Breathlessness'),
    ('At Rest', 'Breathlessness'),
    ('Nocturnal', 'Breathlessness')
) AS ss(NAME, SYMPTOM_NAME)
JOIN SYMPTOMS s ON s.NAME = ss.SYMPTOM_NAME
WHERE (SELECT COUNT(*) FROM SUB_SYMPTOMS) = 0;

-- Seed diagnoses
INSERT INTO DIAGNOSES (NAME, CATEGORY)
SELECT * FROM (VALUES
    ('Viral Fever', 'Infectious'),
    ('Viral Flu', 'Infectious'),
    ('Upper Respiratory Infection', 'Respiratory'),
    ('Lower Respiratory Infection', 'Respiratory'),
    ('Bronchitis', 'Respiratory'),
    ('Pneumonia', 'Respiratory'),
    ('Asthma', 'Respiratory'),
    ('Gastritis', 'Gastrointestinal'),
    ('Acid Reflux (GERD)', 'Gastrointestinal'),
    ('Gastroenteritis', 'Gastrointestinal'),
    ('Urinary Tract Infection', 'Urological'),
    ('Hypertension', 'Cardiovascular'),
    ('Type 2 Diabetes', 'Metabolic'),
    ('Migraine', 'Neurological'),
    ('Allergic Rhinitis', 'Allergic'),
    ('Dermatitis', 'Dermatological'),
    ('Tonsillitis', 'ENT'),
    ('Sinusitis', 'ENT'),
    ('Otitis Media', 'ENT'),
    ('Dengue Fever', 'Infectious')
) AS t(NAME, CATEGORY)
WHERE (SELECT COUNT(*) FROM DIAGNOSES) = 0;
