-- Only seed if table is empty (first run)
INSERT INTO MEDICINES (NAME, CATEGORY)
SELECT * FROM (VALUES
    ('Paracetamol', 'Analgesic'),
    ('Ibuprofen', 'NSAID'),
    ('Amoxicillin', 'Antibiotic'),
    ('Azithromycin', 'Antibiotic'),
    ('Ciprofloxacin', 'Antibiotic'),
    ('Metformin', 'Antidiabetic'),
    ('Glimepiride', 'Antidiabetic'),
    ('Amlodipine', 'Antihypertensive'),
    ('Losartan', 'Antihypertensive'),
    ('Telmisartan', 'Antihypertensive'),
    ('Atorvastatin', 'Statin'),
    ('Rosuvastatin', 'Statin'),
    ('Omeprazole', 'Antacid'),
    ('Pantoprazole', 'Antacid'),
    ('Ranitidine', 'Antacid'),
    ('Domperidone', 'Antiemetic'),
    ('Ondansetron', 'Antiemetic'),
    ('Cetirizine', 'Antihistamine'),
    ('Levocetirizine', 'Antihistamine'),
    ('Fexofenadine', 'Antihistamine'),
    ('Montelukast', 'Antiasthmatic'),
    ('Salbutamol', 'Bronchodilator'),
    ('Prednisolone', 'Corticosteroid'),
    ('Dexamethasone', 'Corticosteroid'),
    ('Methylprednisolone', 'Corticosteroid'),
    ('Aspirin', 'Antiplatelet'),
    ('Clopidogrel', 'Antiplatelet'),
    ('Metoprolol', 'Beta-blocker'),
    ('Atenolol', 'Beta-blocker'),
    ('Propranolol', 'Beta-blocker'),
    ('Diclofenac', 'NSAID'),
    ('Naproxen', 'NSAID'),
    ('Tramadol', 'Analgesic'),
    ('Gabapentin', 'Anticonvulsant'),
    ('Pregabalin', 'Anticonvulsant'),
    ('Alprazolam', 'Anxiolytic'),
    ('Diazepam', 'Anxiolytic'),
    ('Sertraline', 'Antidepressant'),
    ('Fluoxetine', 'Antidepressant'),
    ('Escitalopram', 'Antidepressant'),
    ('Levothyroxine', 'Thyroid'),
    ('Metronidazole', 'Antibiotic'),
    ('Doxycycline', 'Antibiotic'),
    ('Cephalexin', 'Antibiotic'),
    ('Cefixime', 'Antibiotic'),
    ('Rabeprazole', 'Antacid'),
    ('Sucralfate', 'Gastroprotective'),
    ('Lactulose', 'Laxative'),
    ('Bisacodyl', 'Laxative'),
    ('Iron Folic Acid', 'Supplement'),
    ('Calcium + Vitamin D3', 'Supplement'),
    ('Vitamin B Complex', 'Supplement'),
    ('Multivitamin', 'Supplement'),
    ('Insulin Glargine', 'Antidiabetic'),
    ('Sitagliptin', 'Antidiabetic'),
    ('Pioglitazone', 'Antidiabetic'),
    ('Furosemide', 'Diuretic'),
    ('Hydrochlorothiazide', 'Diuretic'),
    ('Spironolactone', 'Diuretic'),
    ('Warfarin', 'Anticoagulant')
) AS t(NAME, CATEGORY)
WHERE (SELECT COUNT(*) FROM MEDICINES) = 0;
